# DNA Service
kind: Service
apiVersion: v1
metadata:
  name: dna
  namespace: ${CICD_GIT_BRANCH}
spec:
  selector:
    app: dna
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
# Prisma Service
kind: Service
apiVersion: v1
metadata:
  name: prisma
  namespace: ${CICD_GIT_BRANCH}
spec:
  selector:
    app: prisma
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4466
      targetPort: 4466
---
# Prisma Mongo Service
kind: Service
apiVersion: v1
metadata:
  name: prisma-db
  namespace: ${CICD_GIT_BRANCH}
spec:
  selector:
    app: prisma-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
# DNA Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dna
  namespace: ${CICD_GIT_BRANCH}
  labels:
    app: dna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dna
  template:
    metadata:
      annotations:
        commit-ref: ${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
        pipeline-ref: ${CICD_EXECUTION_ID}
      labels:
        app: dna
    spec:
      # Allow to pull image from gitlab repo
      imagePullSecrets:
      - name: gitlab
      containers:
      - name: dna
        # Registry image
        image: my.regirstry.com/dna:${CICD_GIT_BRANCH}
        imagePullPolicy: Always
        env:
          - name: MASTERKEY
            valueFrom:
              secretKeyRef:
                key: masterkey
                name: ${CICD_GIT_BRANCH}
          - name: MARIA_HOST
            valueFrom:
              secretKeyRef:
                key: db-host
                name: ${CICD_GIT_BRANCH}
          - name: MARIA_USER
            valueFrom:
              secretKeyRef:
                key: db-user
                name: ${CICD_GIT_BRANCH}
          - name: MARIA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db-password
                name: ${CICD_GIT_BRANCH}
          - name: MARIA_DATABASE
            valueFrom:
              secretKeyRef:
                key: db-name
                name: ${CICD_GIT_BRANCH}
          - name: MARIA_CONNEXION_LIMIT
            valueFrom:
              secretKeyRef:
                key: db-connexion-limit
                name: ${CICD_GIT_BRANCH}
          - name: MARIA_PORT
            valueFrom:
              secretKeyRef:
                key: db-port
                name: ${CICD_GIT_BRANCH}
---
# Prisma Deployment
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: prisma
  namespace: ${CICD_GIT_BRANCH}
  labels:
    app: prisma
spec:
  podManagementPolicy: OrderedReady
  # replicas: 1
  selector:
    matchLabels:
      app: prisma
  serviceName: ""
  template:
    metadata:
      annotations:
        commit-ref: ${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
        pipeline-ref: ${CICD_EXECUTION_ID}
      labels:
        app: prisma
    spec:
      containers:
      - name: prisma
        image: prismagraphql/prisma:1.33
        imagePullPolicy: Always
        env:
          - name: PRISMA_CONFIG
            value: |
              port: 4466
              databases:
                default:
                  connector: mongo
                  uri: mongodb://prisma-db
  updateStrategy:
    type: RollingUpdate
#Add Persistent DB
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prisma-db
#   namespace: ${CICD_GIT_BRANCH}
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: default
#   volumeMode: Filesystem
---
# MongoDB Deployment
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: prisma-db
  namespace: ${CICD_GIT_BRANCH}
spec:
  selector:
    matchLabels:
      app: prisma-db
  serviceName: ""
  template:
    metadata:
      labels:
       app: prisma-db
    spec:
      containers:
      - args:
        image: bitnami/mongodb:4.1
        imagePullPolicy: Always
        name: prisma-db
        volumeMounts:
        - mountPath: /bitnami
          name: prisma-db
      volumes:
      - name: prisma-db
        persistentVolumeClaim:
          claimName: prisma-db
  updateStrategy:
    type: RollingUpdate
---
kind: Service
apiVersion: v1
metadata:
 labels:
   app: prisma
   kubernetes.io/cluster-service: "true"
 name: prisma-admin
 namespace: ${CICD_GIT_BRANCH}
spec:
 type: ClusterIP
 selector:
   app: prisma
 ports:
 - name: http
   port: 80
   targetPort: 4466
